export const OPEN_ALERT_DIALOG_BOX = "OPEN_ALERT_DIALOG_BOX";
export const CLOSE_ALERT_DIALOG_BOX = "CLOSE_ALERT_DIALOG_BOX";
export const OPEN_ALERT_POPUP = "OPEN_ALERT_POPUP";
export const CLOSE_ALERT_POPUP = "CLOSE_ALERT_POPUP";
